apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 02-model-training-v2-pvc
  namespace: ic-shared-rag-llm
  labels:
    app: elyra-model-training
    component: storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-artifacts-pvc
  namespace: ic-shared-rag-llm
  labels:
    app: ml-pipeline
    component: model-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem